'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsBatches
    Inherits DataSet
    
    Private tableBATCHES As BATCHESDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("BATCHES")) Is Nothing) Then
                Me.Tables.Add(New BATCHESDataTable(ds.Tables("BATCHES")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property BATCHES As BATCHESDataTable
        Get
            Return Me.tableBATCHES
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsBatches = CType(MyBase.Clone,dsBatches)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("BATCHES")) Is Nothing) Then
            Me.Tables.Add(New BATCHESDataTable(ds.Tables("BATCHES")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableBATCHES = CType(Me.Tables("BATCHES"),BATCHESDataTable)
        If (Not (Me.tableBATCHES) Is Nothing) Then
            Me.tableBATCHES.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsBatches"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsBatches.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableBATCHES = New BATCHESDataTable
        Me.Tables.Add(Me.tableBATCHES)
    End Sub
    
    Private Function ShouldSerializeBATCHES() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub BATCHESRowChangeEventHandler(ByVal sender As Object, ByVal e As BATCHESRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BATCHESDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnBCODE As DataColumn
        
        Private columnSUBJECT As DataColumn
        
        Private columnSTDATE As DataColumn
        
        Private columnENDDATE As DataColumn
        
        Private columnTIMING As DataColumn
        
        Private columnNOSESSIONS As DataColumn
        
        Private columnTFEE As DataColumn
        
        Private columnLFEE As DataColumn
        
        Friend Sub New()
            MyBase.New("BATCHES")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property BCODEColumn As DataColumn
            Get
                Return Me.columnBCODE
            End Get
        End Property
        
        Friend ReadOnly Property SUBJECTColumn As DataColumn
            Get
                Return Me.columnSUBJECT
            End Get
        End Property
        
        Friend ReadOnly Property STDATEColumn As DataColumn
            Get
                Return Me.columnSTDATE
            End Get
        End Property
        
        Friend ReadOnly Property ENDDATEColumn As DataColumn
            Get
                Return Me.columnENDDATE
            End Get
        End Property
        
        Friend ReadOnly Property TIMINGColumn As DataColumn
            Get
                Return Me.columnTIMING
            End Get
        End Property
        
        Friend ReadOnly Property NOSESSIONSColumn As DataColumn
            Get
                Return Me.columnNOSESSIONS
            End Get
        End Property
        
        Friend ReadOnly Property TFEEColumn As DataColumn
            Get
                Return Me.columnTFEE
            End Get
        End Property
        
        Friend ReadOnly Property LFEEColumn As DataColumn
            Get
                Return Me.columnLFEE
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As BATCHESRow
            Get
                Return CType(Me.Rows(index),BATCHESRow)
            End Get
        End Property
        
        Public Event BATCHESRowChanged As BATCHESRowChangeEventHandler
        
        Public Event BATCHESRowChanging As BATCHESRowChangeEventHandler
        
        Public Event BATCHESRowDeleted As BATCHESRowChangeEventHandler
        
        Public Event BATCHESRowDeleting As BATCHESRowChangeEventHandler
        
        Public Overloads Sub AddBATCHESRow(ByVal row As BATCHESRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddBATCHESRow(ByVal BCODE As String, ByVal SUBJECT As String, ByVal STDATE As Date, ByVal ENDDATE As Date, ByVal TIMING As String, ByVal NOSESSIONS As Decimal, ByVal TFEE As Decimal, ByVal LFEE As Decimal) As BATCHESRow
            Dim rowBATCHESRow As BATCHESRow = CType(Me.NewRow,BATCHESRow)
            rowBATCHESRow.ItemArray = New Object() {BCODE, SUBJECT, STDATE, ENDDATE, TIMING, NOSESSIONS, TFEE, LFEE}
            Me.Rows.Add(rowBATCHESRow)
            Return rowBATCHESRow
        End Function
        
        Public Function FindByBCODE(ByVal BCODE As String) As BATCHESRow
            Return CType(Me.Rows.Find(New Object() {BCODE}),BATCHESRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As BATCHESDataTable = CType(MyBase.Clone,BATCHESDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New BATCHESDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnBCODE = Me.Columns("BCODE")
            Me.columnSUBJECT = Me.Columns("SUBJECT")
            Me.columnSTDATE = Me.Columns("STDATE")
            Me.columnENDDATE = Me.Columns("ENDDATE")
            Me.columnTIMING = Me.Columns("TIMING")
            Me.columnNOSESSIONS = Me.Columns("NOSESSIONS")
            Me.columnTFEE = Me.Columns("TFEE")
            Me.columnLFEE = Me.Columns("LFEE")
        End Sub
        
        Private Sub InitClass()
            Me.columnBCODE = New DataColumn("BCODE", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnBCODE)
            Me.columnSUBJECT = New DataColumn("SUBJECT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSUBJECT)
            Me.columnSTDATE = New DataColumn("STDATE", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSTDATE)
            Me.columnENDDATE = New DataColumn("ENDDATE", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnENDDATE)
            Me.columnTIMING = New DataColumn("TIMING", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIMING)
            Me.columnNOSESSIONS = New DataColumn("NOSESSIONS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNOSESSIONS)
            Me.columnTFEE = New DataColumn("TFEE", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTFEE)
            Me.columnLFEE = New DataColumn("LFEE", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLFEE)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnBCODE}, true))
            Me.columnBCODE.AllowDBNull = false
            Me.columnBCODE.Unique = true
        End Sub
        
        Public Function NewBATCHESRow() As BATCHESRow
            Return CType(Me.NewRow,BATCHESRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New BATCHESRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(BATCHESRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.BATCHESRowChangedEvent) Is Nothing) Then
                RaiseEvent BATCHESRowChanged(Me, New BATCHESRowChangeEvent(CType(e.Row,BATCHESRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.BATCHESRowChangingEvent) Is Nothing) Then
                RaiseEvent BATCHESRowChanging(Me, New BATCHESRowChangeEvent(CType(e.Row,BATCHESRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.BATCHESRowDeletedEvent) Is Nothing) Then
                RaiseEvent BATCHESRowDeleted(Me, New BATCHESRowChangeEvent(CType(e.Row,BATCHESRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.BATCHESRowDeletingEvent) Is Nothing) Then
                RaiseEvent BATCHESRowDeleting(Me, New BATCHESRowChangeEvent(CType(e.Row,BATCHESRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveBATCHESRow(ByVal row As BATCHESRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BATCHESRow
        Inherits DataRow
        
        Private tableBATCHES As BATCHESDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableBATCHES = CType(Me.Table,BATCHESDataTable)
        End Sub
        
        Public Property BCODE As String
            Get
                Return CType(Me(Me.tableBATCHES.BCODEColumn),String)
            End Get
            Set
                Me(Me.tableBATCHES.BCODEColumn) = value
            End Set
        End Property
        
        Public Property SUBJECT As String
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.SUBJECTColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.SUBJECTColumn) = value
            End Set
        End Property
        
        Public Property STDATE As Date
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.STDATEColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.STDATEColumn) = value
            End Set
        End Property
        
        Public Property ENDDATE As Date
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.ENDDATEColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.ENDDATEColumn) = value
            End Set
        End Property
        
        Public Property TIMING As String
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.TIMINGColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.TIMINGColumn) = value
            End Set
        End Property
        
        Public Property NOSESSIONS As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.NOSESSIONSColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.NOSESSIONSColumn) = value
            End Set
        End Property
        
        Public Property TFEE As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.TFEEColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.TFEEColumn) = value
            End Set
        End Property
        
        Public Property LFEE As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableBATCHES.LFEEColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBATCHES.LFEEColumn) = value
            End Set
        End Property
        
        Public Function IsSUBJECTNull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.SUBJECTColumn)
        End Function
        
        Public Sub SetSUBJECTNull()
            Me(Me.tableBATCHES.SUBJECTColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSTDATENull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.STDATEColumn)
        End Function
        
        Public Sub SetSTDATENull()
            Me(Me.tableBATCHES.STDATEColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsENDDATENull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.ENDDATEColumn)
        End Function
        
        Public Sub SetENDDATENull()
            Me(Me.tableBATCHES.ENDDATEColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTIMINGNull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.TIMINGColumn)
        End Function
        
        Public Sub SetTIMINGNull()
            Me(Me.tableBATCHES.TIMINGColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNOSESSIONSNull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.NOSESSIONSColumn)
        End Function
        
        Public Sub SetNOSESSIONSNull()
            Me(Me.tableBATCHES.NOSESSIONSColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTFEENull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.TFEEColumn)
        End Function
        
        Public Sub SetTFEENull()
            Me(Me.tableBATCHES.TFEEColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsLFEENull() As Boolean
            Return Me.IsNull(Me.tableBATCHES.LFEEColumn)
        End Function
        
        Public Sub SetLFEENull()
            Me(Me.tableBATCHES.LFEEColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class BATCHESRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As BATCHESRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As BATCHESRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As BATCHESRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
